### ISSUE TITLE
[doc] make a proper "installation" readme that is more thorough

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1128]

**Comment by Christopher876** [comment]
So, I was looking around to help with this project because I wanted to learn more about decompilation and also since this is my favorite game and all. So I guess this is a good place to start.

The Ubuntu dependencies need to be updated. A few of them are not listed there leaving you to have to install them as CMake complains about the missing dependencies.

The additional ones are `libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev`

**Comment by water111** [comment]
Thanks! If you're interested, we also have a discord (https://discord.gg/gdMSQ986) where we discuss development

**Comment by Christopher876** [comment]
> Thanks! If you're interested, we also have a discord (https://discord.gg/gdMSQ986) where we discuss development

Already joined! I'm looking through how all this stuff works right now
