### ISSUE TITLE
[goalc] Typing an umlaut instantly crashes goalc

### ISSUE THREAD

**Issue by Hat-Kid** [open-goal/jak-project#1130]
Typing an umlaut (`ä`, `ö` or `ü`) instantly crashes the REPL.

```
goalc: /home/philip/code/git/jak-project/./common/util/Trie.h:45: static int Trie<T>::idx(char) [with T = std::vector<SymbolInfo>]: Assertion `c >= CHAR_START' failed.
[1]    820678 abort (core dumped)  ./build/goalc/goalc
```

**Comment by ManDude** [comment]
Pretty much any fancy character will do this it seems.

**Comment by water111** [comment]
It looks like this problem is just with the auto-complete stuff. I fixed the prefix tree (the part that was crashing) in https://github.com/water111/jak-project/pull/1138 but there's still something weird going on with the REPL library or the way we've implemented autocomplete.  the character just disappears now, which is annoying, but better than just crashing.

**Comment by xTVaser** [comment]
I can't reproduce this on windows, it looks like our exceptions are not converting to utf-16, but characters don't disappear upon entry (or when pressing tab to complete)
![image](https://user-images.githubusercontent.com/13153231/153728552-8fc16d41-71e0-4a51-948f-534851c2ec75.png)

Maybe this is linux specific?

**Comment by water111** [comment]
looks like this no longer crashes.
