### ISSUE TITLE
[NAN] camera rot is sometimes "NaN" (entering finalboss)

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1147]

**Comment by water111** [comment]
I did look at this quickly and it's something going wrong in one of the orientation math functions as the camera does the really fast transition to looking down at the elevator platform.  I'd bet that it's something like the punch glitch and we should mess with the rounding mode or just figure out where the NaNs are coming from and patch it.

**Comment by water111** [comment]
I'm also curious if this is the same issue as the weird camera movement in the fj temple

**Comment by water111** [comment]
To summarize - we think all of these are related to the same bug:
- The camera (and target) vel go to NaN
- It's believed that this can cause a mips2c crash somehow, or just a black screen
- It can happen when starting the elevator
- It can happen when punching off the platform (wait until it is most of the way to the final boss)

**Comment by doctashay** [comment]
Related to this issue I receive a unique and consistent crash every time I take the platform to the final boss fight, and punch off the ledge as soon as the new checkpoint is created. Switching between checkpoints directly causes this issue but it also looks like this bug can be triggered just by playing normally instead of hopping checkpoints.

Here's the output from this error: 

```\game/mips2c/mips2c_private.h:1146: Assertion failed: (sadr + 16 * qwc) <= 0x4000
Function: void __cdecl Mips2C::spad_to_dma_no_sadr_off(void *, u32, u32, u32)```

**Comment by ManDude** [comment]
One of the actors seems to be causing this. I am assuming it must be robotboss based on some tests I did. Have not investigated further yet.

**Comment by water111** [comment]
seems like https://github.com/open-goal/jak-project/pull/1252 fixed it.
