### ISSUE TITLE
[kernel] expand symbol table

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1172]
Jak 1 already uses ~7950 symbols of the ~8100 usable in the symbol table. While I doubt we'll run into the issue of running out of symbols (but it's totally possible), anyone wanting to add anything to the game likely will. So we should probably think about making it possible to expand the memory if necessary. Only issues I can think of is with `symbol->string`, which will fail for any code where we didn't convert it properly into that form and it still says `+ 0xff38`. I also don't know if the symbol hashing supports more symbols.

**Comment by water111** [comment]
the hashing algorithm is easy to expand (especially if you just make the table 2x larger).

The more annoying part is that some instructions that are patched by the linker have 16-bit offsets, so I think we'll need to switch to different instructions and revise the linker format.

**Comment by ManDude** [comment]
It looks like RIP-relative addressing supports up to 32-bit offsets (536870912 symbols!!), but yeah it's a different kind of instruction altogether.

**Comment by water111** [comment]
ah, turns out I remembered wrong and we do use 32-bit offsets for everything. The three for the symbol table are `lea_reg_plus_off32` `store32_gpr64_gpr64_plus_gpr64_plus_s32` (what was I thinking with this name), and `load32s_gpr64_gpr64_plus_gpr64_plus_s32` all can have 32-bit offsets.  And it looks like the linker would work with this too.
