### ISSUE TITLE
[bones] bad lod hack

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1193]
Aside from the plant boss and kermit always having buggy bones, you can trigger SPS on a lot more things by messing with the LODs. This is easy to do if you force LODs to lowest quality when things spawn, then later force it to high quality.
![image](https://user-images.githubusercontent.com/7569514/155462045-d7b535e1-be7e-4cc6-b2e8-aa0a85501ffc.png)
![image](https://user-images.githubusercontent.com/7569514/155462238-adf83f46-e10c-4742-b984-7d491e781d51.png)
![image](https://user-images.githubusercontent.com/7569514/155462514-c808ef73-26c0-40c0-be79-de6066c885d8.png)

This goes away once the actors animate a single time, which for doors is a little tricky since you need to make them open/close.

**Comment by water111** [comment]
I think the issue on changing lods might be because we're overriding the lods in the wrong way. The game has a check that re-runs the "matrix engine" if you change lods but aren't running an animation:
https://github.com/open-goal/jak-project/blob/master/goal_src/engine/draw/drawable.gc#L753
but our lod override will skip this check, so it makes sense that we get garbage until the next animation frame.

The number of joints to update from the animation is chosen here:
https://github.com/open-goal/jak-project/blob/71f08fbd8c25d9cc2b0f9b3bc19027c03510b843/goal_src/engine/draw/process-drawable.gc#L316
where `mgeo` is set to a specific LOD's geometry in `lod-set!`.

The plant boss/frog are some other issue. I'd guess that it's an issue with the `joint-mod` stuff - they seem to be using some weird ones.

**Comment by ManDude** [comment]
I'll see where I can move the lod hacks then. It's interesting that both result in the same kind of top left spike issue.

**Comment by water111** [comment]
plant boss and frog are fixed (https://github.com/open-goal/jak-project/pull/1200)
