### ISSUE TITLE
[eye] filtering

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1206]
![image](https://user-images.githubusercontent.com/7569514/155858344-629c2f8f-d301-4791-b8e1-b35c9478c2d1.png)

I'm not sure our texture filtering for the eyes is totally correct (well actually it doesn't look like there's any filtering at all). Sometimes it looks kinda weird. We can probably just apply some quick linear filtering.
![image](https://user-images.githubusercontent.com/7569514/155858383-467b71b1-f4da-49e9-841b-48ab41e82654.png)

**Comment by water111** [comment]
emulator filtering on pupil (ours isn't as round)
![image](https://user-images.githubusercontent.com/48171810/156492086-2091d568-a9c8-45c5-b4c0-83d108314c09.png)

bird lady off-by-one (emulator doesn't have the little gap) maybe we should check the software renderer because pcsx2 is also off sometimes.
![image](https://user-images.githubusercontent.com/48171810/156492373-e64029ce-cd8f-4d4b-b074-1fa76c5a9c45.png)

**Comment by ManDude** [comment]
software mode looks fine:
![image](https://user-images.githubusercontent.com/7569514/156494795-65241422-3722-4bb7-8496-796033320372.png)

**Comment by water111** [comment]
both fixed in https://github.com/open-goal/jak-project/pull/1219
