### ISSUE TITLE
[game] boggy tether spawning issues

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1248]

**Comment by water111** [comment]
![image](https://user-images.githubusercontent.com/48171810/160211940-51443f9a-898c-44c7-89d4-fdd9228c0038.png)
looks like it's there, but not being drawn.

I couldn't get this to reproduce by playing normally, but if you stand in the yellow eco vent you'd normally use to shoot the last boulder and do a "Reset Actors", you can get into this state.

**Comment by ManDude** [comment]
is the drawable engine full?

**Comment by water111** [comment]
No, it only has 53 out of 840.

Also interesting, it thinks it's being drawn. It also belongs to village2, which could be related.
```
gc> (debug-print (the entity-actor (entity-by-name "swamp-tetherrock-15")) #f (the type #f))
 3899  #x01dd9e54    swamp-tetherrock-15   10954  41  vi2 #x0080 :trans   2111574.5000     59407.0742  -7935225.0000  :pr #x001a7384 swamp-tethe~ swamp-tetherrock-idle  2704/ 2704 rd0
```

**Comment by ManDude** [comment]
hmmmm that could be interesting. The "all actors" button simply makes the vis test for entities always pass, but I noticed that you need to actually be inside boxes for it to work. For example when you load in snowy mountain you need to actually go inside it for all of the snow actors to spawn. Maybe it's related to that? I didn't bother with getting rid of this limitation though I doubt it's difficult.

**Comment by water111** [comment]
Some other interesting things:
- you have to blow up the first boulder for this to happen
- after doing a "reset actors" after blowing up the first boulder, the remaining boulders get messed up
- I don't think it's a merc problem because the collision geometry for the boulder is missing too.

After blowing up the first boulder and doing reset actors, it's possible to see some garbage polygons
![image](https://user-images.githubusercontent.com/48171810/160214063-a52b87e8-1a83-4bfc-9514-0641723d9155.png)

I do see:
```
tension: NaN
```
which makes me think something math-related in `swamp-blimp.gc` is going wrong.

**Comment by ManDude** [comment]
Just wondering, do you have high quality actor LODs turned on? Or are you using the PS2 LODs? The blimp looks kinda weird when it's at highest lod.

**Comment by water111** [comment]
It was bad either way.  

I have a fix now. Here's the process I went through, in case anybody is curious or wants to do this type of debugging. 

I started by inspecting some random values in the rock, hoping to find something that is causing NaNs in bones.  The bones are very likely bad because both the graphics and collision mesh are bad. (I confirmed that `ftoi`s in MERC that are the final conversion for vertex positions have NaNs as inputs, so it's very likely NaNs in bones, and not just incorrect positions)

I found `tension-pt` has NaNs:
```
gc> (inspect (-> (the swamp-tetherrock (-> (the entity-actor (entity-by-name "swamp-tetherrock-15")) extra process)) tension-pt))
[001ddd90] vector
	[         NaN] [         NaN] [         NaN] [      1.0000]
1957264        #x1ddd90              0.0000        244658
```

I didn't see anywhere that could set this to NaNs, so I ran this in GDB:
```
(gdb) watch *0x21231DDD90
Hardware watchpoint 1: *0x21231DDD90
(gdb) c
Continuing.
```
first hit after spawning:
```
Thread 5 "gk" hit Hardware watchpoint 1: *0x21231DDD90

Old value = -4194304
New value = 0
0x0000002123163ff6 in ?? ()
```
which makes sense, something resets that point.

Then:
```
Thread 5 "gk" hit Hardware watchpoint 1: *0x21231DDD90

Old value = 0
New value = -4194304
0x0000002124fd7210 in ?? ()
(gdb) 
```

setting a breakpoint at this address:
```
gr> (set! (-> (the (pointer uint8) #x1FD7210)) #xcc)
```

Which points to:
```
(set! (-> (the-as swamp-rope a0-4) frame vector-overlay quad) (-> self root trans quad))
```
which has the wrong type.  After fixing:

```
        (when a0-4
          (set! (-> (the-as swamp-tetherrock a0-4) tension) (-> self frame value))
          (set! (-> (the-as swamp-tetherrock a0-4) tension-pt quad) (-> self root trans quad))
          )
```
it makes more sense - it's setting the `tension-point` of the rock to the rope's origin.

These NaNs come from:
```
(vector<-cspace! (-> self root trans) (-> self parent-override 0 node-list data (-> self parent-rp)))
```
where `self` is a `swamp-rope` and the `parent-override` is the `swamp-blimp`.

The `swamp-blimp`'s bones are NaN-filled, but I'm guessing it's a problem in the blimp code and not bones itself.The blimp has `joint-mods` that let you modify the input to bone calculation (for stuff like turning jak's head, rotating a propeller, and other stuff not in joint-anims).

I first noticed this is bad:
```
gc> (inspect (-> (the swamp-blimp (-> (the entity-actor (entity-by-type swamp-blimp)) extra process)) gondola-tilt-oscillator target))
[001de950] vector
	[         NaN] [     -3.9999] [         NaN] [      1.0000]
1960272        #x1de950              0.0000        245034
```
and traced this back to:
```
                (vector-!
                  (the-as vector (-> self gondola-tilt-oscillator))
                  (the-as vector (-> self gondola-tilt-oscillator))
                  (vector<-cspace!
                    (new 'stack-no-clear 'vector)
                    (-> self node-list data (-> (the-as swamp-rope s4-0) parent-rp))
                    )
                  )
```

I checked the bones for this  `vector<-cspace!` that was producing the first NaNs and they were all zero... which is the default value until the matrix engine runs.

Does it make sense that the bones can be 0's here? I think so:
- First, break at least one boulder.
- Then cause the blimp to respawn (die, or go very away and come back)
- `init-from-entity! swamp-blimp` is called to spawn the blimp
- this calls `(initialize-skeleton obj *swamp-blimp-sg* '())` which allocates the bones (default values of 0 here) 
- this calls `(swamp-blimp-setup)` before `go`ing to the initial state
- this finds the ropes and does a `vector<-cspace!` to find the position of the bone
- this does:
```
    ...
    (.lvf vf2 (&-> (-> arg1 bone) transform vector 3 quad))
    (.div.vf Q vf0 vf2 :fsf #b11 :ftf #b11)
    ...
    (.mul.vf vf2 vf2 Q :mask #b111)
```
which will give NaNs on x86, but 0's on PS2, if the transform is all 0 (which it is, because we haven't run `ja-post` and stuff yet.)
Once the NaNs get in here, it never recovers.

Changing this to return 0, 0, 0, 1 if the divisor is 0 fixes it:

```
    ;; ADDED
    ;; there's a bug in swamp-blimp where they vector<-cspace!
    ;; on some default-initialized-to-zero bones
    ;; we have to return 0s for this to avoid NaNs getting everywhere.
    (let ((temp (new-stack-vector0)))
      (.svf (&-> temp quad) vf2)
      (when (= (-> temp w) 0.0)
        (set-vector! arg0 0. 0. 0. 1.)
        (return arg0)
        )
      )
```
