### ISSUE TITLE
[game] [release 0.1.3] [windows] Toggling certain options in the Render debug menu crashes the game.

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/jak-project#1382]
Observed with:

TFRAG TIE TEXTURES 
and
ALPHA TEXTURES

**Comment by Zedb0T** [comment]
"All on" Does not toggle generic-tie - this may not be a bug but figured Id mentioned it while Im here

**Comment by water111** [comment]
Will be fixed by #1385. It won't crash now, but turning off textures won't behave exactly like on the ps2.

The generic-tie thing happens in the game too - it's actually controlled by a different system from the rest of the renderers, for some unknown reason. The debug menu can toggle it, but the all on/all off doesn't set it.
