### ISSUE TITLE
ram boss disappears randomly

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1394]

**Comment by water111** [comment]
he's there, just far away:
```
gc> (let ((p (the ram-boss (process-by-name "ram-boss" *active-pool*)))) (inspect (-> p root trans)))
[001ca400] vector
	[         NaN] [1023790.7500] [         NaN] [      1.0000]
1876992        #x1ca400              0.0000        234624
```

**Comment by ManDude** [comment]
yeah, i think something similar happens whenever an enemy fails the find-ground test. failing the test is normal, disappearing from that isn't.

**Comment by water111** [comment]
so far, I've only been able to trigger this by running around in a way that makes the ram boss respawn

**Comment by ManDude** [comment]
I just stay on top of the ram and eventually he disappears

**Comment by water111** [comment]
ah yep, me too. how much do you want to bet it's the stupid joint mod stuff again

**Comment by ManDude** [comment]
Now that you say that, I think the rats are also enemies that look at you.

**Comment by water111** [comment]
well, I was wrong about the joint mod stuff... 

but the nan comes from `integrate-for-enemy-with-move-to-ground`, which definitely calls `move-to-ground` somehwere.

**Comment by water111** [comment]
how we get to a nan in `trans`:
- happens in `nav-enemy-patrol` state's `post`
- `nav-enemy`'s `TODO-RENAME-38` calls `integrate-for-enemy-with-move-to-ground` with NaN in `transv`
- the `transv` becomes NaN in `dummy-41` because `(-> self nav travel)` is NaN
- `dummy-40` calls `dummy-11` on the `nav-control`, calls `dummy-13`, calls `TODO-RENAME-33` which calls `TODO-ASM-32`
- this function reads the sphere locations that have been added from "users" of the nav-mesh, including `babak-286`
- somehow, babak-286's sphere is NaN

So I don't think the issue is anywhere here, the real cause is the babak disappearing.
