### ISSUE TITLE
Arm compatibility under Linux 

### ISSUE THREAD

**Issue by burt111** [open-goal/jak-project#1411]
Was wondering if any other platform would get support in the future or is x86_64 the only platform planned would be amazing to get this running on non x86_64 hardware

**Comment by coreybruce** [comment]
Now that you are building for Mac OS Arm64 is Linux arm64 next @Hat-Kid ?

**Comment by coreybruce** [comment]
> Not for the time being, no.
> 
> The reason we have macOS ARM builds now is that Rosetta 2 allows you to run software designed for x86-64 processors on Apple silicon, which makes it possible to run OpenGOAL on those devices.
> 
> However, the OpenGOAL compiler still does not actually emit ARM code, so there is little reason to have ARM builds for any other platform right now.

Well that's fine because we have Box64 and Fex to cover that, I already was testing it on the pi 5 as "under powered" as it is but it can run on arm hardware with Linux thanks to these projects

The only issue specifically I ran into on the pi 5 was a shader issue, I know this would technically be a separate issue I could file if it's possible to look at
https://github.com/ptitSeb/box64/issues/2548#issuecomment-2816671580

Technically this would be a concept to push toward
Linux arm64
