### ISSUE TITLE
[Graphics] Missing sprite-distort (blur effects)

### ISSUE THREAD

**Issue by skullpanda86** [open-goal/jak-project#1485]
### Describe the Bug

So from what I can tell the depth of field effects around torches and portals aren't being rendered at all.

### How To Reproduce

By running it.

### Expected Behavior

Effect not being rendered
![JAK pc OGL](https://user-images.githubusercontent.com/10225093/174466220-08f9e498-1dd0-4974-9dda-3fec09848115.jpg)

Correct effect using the SW renderer in PCSX2 
![Jak ps2 SW](https://user-images.githubusercontent.com/10225093/174466222-e898d940-7d4c-483c-8e0a-2b8ff395e270.jpg)

### Operating System

Windows 11

### OpenGOAL Version

Release

### Game Version

NTSC 1.0 (black label)

**Comment by water111** [comment]
yep, there's a renderer called `sprite-distort` that does this effect on torches, warp gates, and platforms, and it's not implemented at all in the port yet.  It's a simple effect, but can be annoying to implement because it has to read the framebuffer.

I plan to do it eventually, but probably not soon.

**Comment by ManDude** [comment]
Took a while for someone to notice!

**Comment by water111** [comment]
added in https://github.com/open-goal/jak-project/pull/1626
