### ISSUE TITLE
[request] Guide on how to install this on the steam deck

### ISSUE THREAD

**Issue by acrylicus** [open-goal/jak-project#1546]
### What feature is your idea related to?

A good guide on how to install this on the steam deck 

### Describe the solution you'd like.

An addition to the "getting started on linux" section to include the nuances of Steam Decks modified Arch OS - and any considerations specific to the platform

**Comment by Hat-Kid** [comment]
For the release version, the process is pretty much the same as any other platform: Download the release, use the extractor on the ISO and you're done.

However, trying to actually compile the project on the Steam Deck is not very easy due to its read-only root filesystem. I have tried it before and have not been very successful because of all the different dependencies you need, as the Steam Deck's default packages are quite lacking in that area.
You can force unlock the Deck's read-only filesystem, but I don't believe we should advise end-users to do this in order to compile the game, as not only will all your changes to the filesystem be wiped with the next SteamOS update, you may also brick your install if you're not careful.

I would recommend not bothering with it and just using the release version on the Deck (or the launcher once it's ready).

**Comment by branrollins** [comment]
I followed Fan The Deck's guide at https://www.youtube.com/watch?v=Cv7mlCSHKxc&t=647s and got it working without issue.  Don't recall having to do anything permission related either.  I did install to the internal SSD rather than a MicroSD so consider that.   I did have issues with the more recent versions though and had to revert back to 0.1.13 I believe.   0.1.21 gave me an access denied message when trying to use the extractor.

**Comment by DankeBrutus** [comment]
> I followed Fan The Deck's guide at https://www.youtube.com/watch?v=Cv7mlCSHKxc&t=647s and got it working without issue. Don't recall having to do anything permission related either. I did install to the internal SSD rather than a MicroSD so consider that. I did have issues with the more recent versions though and had to revert back to 0.1.13 I believe. 0.1.21 gave me an access denied message when trying to use the extractor.

I was having this issue as well. Have you ensured that the extractor, gk, and goalc programs are marked as executables?

**Comment by xTVaser** [comment]
We've since written up a brief guide for how to do this https://opengoal.dev/docs/usage/installation/#linux-steam-deck (most referencing Fan the Deck's video).  

In the future we've talked about ways we can make installing / updating on the steamdeck easier -- as the launcher isn't well suited for a variety of reasons.  But that's a separate issue.
