### ISSUE TITLE
`\c##` escape sequences are converted to special characters when loaded into the subtitle editor

### ISSUE THREAD

**Issue by towai** [open-goal/jak-project#1550]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

This affects the subtitle editor, don't know if it affects anything else. When a subtitle file is parsed that contains a sequence like `\c93` or `\c14` (yes, i found out i'm supposed to use `<TIL>` in this case) the escape sequence is turned into a character, even for `line_utf8`. In the case of `\c93` it becomes a �, but in the case of \c14 it causes a [`Invalid character found on line # of #: 0x14`](https://github.com/open-goal/jak-project/blob/master/common/goos/Reader.cpp#L279) when the repl then tries to make the text segment.

It seems like fixing this might require messing around in the goos code or FontUtils.cpp and I really don't wanna break anything else by trying to fix this. if I'm wrong about that, and this can be avoided just in the case of the subtitle editor, then I'm more than happy to include the necessary changes in #1516 .

### How To Reproduce

Put a line in a subtitle like this:
`  (2226 "SAGE" "YOU CAN'T CONTROL DARK ECO BY ITSELF! EVEN THE PRECURSORS\c93")` (yes, i know, i'm using a chouonpu as an em-dash, but it serves that purpose nicely imo, and a hyphen would look wrong)
Save it, then restart the game. in the file, the escape sequence is present, but in the editor it's now
`  (2226 "SAGE" "YOU CAN'T CONTROL DARK ECO BY ITSELF! EVEN THE PRECURSORS�")` (note: it's rendered as a ? in the editor, but it's not one. also, the character is still rendered as expected in-game.)
if you then save the changes again, the broken character is saved to the subtitle file.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

`\c##` sequences should remain as they are when loaded into the subtitle editor or any other tool that has you editing GOAL strings. i know that characters such as apostrophe are converted to something else for the game, yet they show up in the subtitle editor as apostrophes and are saved back to the file just fine, so the issue seems to be with these escape sequences specifically.

### Operating System

Windows

### OpenGOAL Version

b8bddb

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by towai** [comment]
since i don't know how to approach this one i'm currently working around this by copy-pasting the chouonpu where it's needed, but this is not a perfect solution, in part because that isn't displayed correctly in the subtitle editor either (which might not be fixable by us, since it's an imgui dialog)

**Comment by yodika** [comment]
One question,  does escape sequence mean exit sequence?

Is it possible to say switch the last number with a letter say as f?

/C9F 

another thing in my theory and pondering  as is it possible to add more than one?  

Did the game originally have subtitles? If so can you look at the code for it?

Are you using the same code as show from original ps2 subtitles? Or?

**Comment by towai** [comment]
bro...
> One question, does escape sequence mean exit sequence?

do not know what you mean by this. escape sequences are a thing in programming that let you put certain characters into a string, like `\n` for newline, `\t` for tab, and `\0` for a null character (often whatever's parsing it takes this as a cue that this is the end of the string). `\c40` will tell GOAL to insert the character corresponding to the code hex 40 (64 decimal) at that spot in the string. (that one happens to be the glyph for the label on the circle button. you can also get this with the @ symbol as you can see in [FontUtils.cpp](https://github.com/open-goal/jak-project/blob/master/common/util/FontUtils.cpp#L498).)
> Is it possible to say switch the last number with a letter say as f?
> 
> \C9F (note: ftfy)

well, the numbers are hexadecimal, so in this case, yes, that happens to be a valid number. `\c9G` wouldn't be. all of them are 2 digits exactly.
> another thing in my theory and pondering as is it possible to add more than one?

what
> Did the game originally have subtitles? If so can you look at the code for it?

it did not. it did have code for displaying text when a "hint" is triggered, which is what voice lines are considered. empty hints are played when crossing between levels
> Are you using the same code as show from original ps2 subtitles? Or?

again, original did not have subtitles. some text display code already existed that's used, a lot of what's used to display subtitles is written from scratch.

**Comment by yodika** [comment]
> well, the numbers are hexadecimal, so in this case, yes, that happens to be a valid number. \c9G wouldn't be. all of them are 2 digits exactly. 
Interesting, what happens if you do \c9f? Can you add more letters to signify no extra number?

> it did not. it did have code for displaying text when a "hint" is triggered, which is what voice lines are considered. empty hints are played when crossing between levels.

Wll then that could be the problem then, as it could be too wide, or character limit, I remember this happening on a few games I played, it would glitch, because extra chars were not supported. 

Another thing it could be is it is level specific hint rather than multiple levels, maybe some kind of yes or no statement and if statement.

Have you tried  \0 after the command that is causing issue? It could be there's no fullstop or end command, and it think there's supposed to bit an extra bit for it but it is missing. 
> what
Well like add two \c9f  instead of just one, or multiple for more functions.

**Comment by towai** [comment]
> Interesting, what happens if you do \c9f? Can you add more letters to signify no extra number?

you get お, as you can see by looking in FontUtils.cpp which I linked above. the second part of this doesn't make any sense, but if the reader sees a `\c` and then the next two characters aren't a number it'd probably throw something like "invalid escape sequence".
> Wll then that could be the problem then, as it could be too wide, or character limit, I remember this happening on a few games I played, it would glitch, because extra chars were not supported.

dunno what you're talking about. the subtitle code wraps text correctly. i don't know the size limit for a GOAL string (if there is one) but i don't think i've ever come close.

the other thing i think you might be saying is that the game may not be set up to handle extra characters correctly, which is just wrong. you can give it anything from 00 to FF (255, the max number you can fit in a single byte. GOAL does not use wide (16-bit) characters.)
> Another thing it could be is it is level specific hint rather than multiple levels, maybe some kind of yes or no statement and if statement.

i don't know what this is supposed to mean or have to do with anything.
> Have you tried \0 after the command that is causing issue? It could be there's no fullstop or end command, and it think there's supposed to bit an extra bit for it but it is missing.

termination of strings happens outside what i'm doing and has nothing to do with this issue.
> Well like add two \c9f instead of just one, or multiple for more functions.

you would get... the same character twice, as you might expect.

**Comment by yodika** [comment]
Oh another thing I just remember, those corrupted broken letters remind me of a game I got, which version of the game you using?

It's it English or?

Because thr game I had wouldn't work at at all on my windows pc because it wasn't translated, and that all my files to make the program work were not the same language.

I found out that If I changed the file name of settings file and another the game could launch, however the game was still broken because of the problem persistence.

I would have to change the target address and file names manually in the code and whatever files that send response to the next.

When I tried the launch the game before renaming it shows random jumbled letters and those question mark inside diamond symbols.

Also it said I was missing an dll I think.

Afterwards when it was running, some features wouldn't work, if I tried to place the game normally it would have the test working but then it would stay stuck on that scene and could not go to the next line of text or image.

Idk if this is helpful or not, but something I thought was similar.

**Comment by xTVaser** [comment]
I think a few things are going on that is making this pretty complicated to solve.

First off, the strings in the files are parsed by the Reader, which converts anything with `\c##` to extended ascii, not utf-8

https://github.com/open-goal/jak-project/blob/892e5a6c4940b1fd600d91b9548aeaa886cedd4e/common/goos/Reader.cpp#L666-L671

Then this is fed into functions that assume the string is utf-8...but it's not

The `g_encode_info_jak1` is a mapping of utf-8 characters to the codes, so I think everything will mostly work -- but the core problem needs to be solved at the Reader level.  Convert to utf-8 using the same mapping instead of extended ascii -- I have no idea if this will break other assumptions.

**Comment by ManDude** [comment]
It looks like `convert_utf8_to_game` doesn't handle the `\c` escape sequence. I think that's the issue.

**Comment by ManDude** [comment]
Nevermind, typing the escape sequence directly in the text file compiles just fine. it is an editor issue then.

**Comment by ManDude** [comment]
ok so the issue is that the escape sequence is converted way too soon
