### ISSUE TITLE
[gameplay] ocean glitches when dropping frames

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#1554]
I think when the time ratio changes, the ocean pattern jumps.

**Comment by Brent-Hickey** [comment]
Crap I think this is because I scaled `integral-frame-counter` by `time-adjust-ratio`, which is affected by lag via `set-time-ratios` (and integral-frame-counter is already accounting for lag because it counts by `time-ratio`). It does need to be scaled for high fps but I think it's being doubly affected by lag now which I didn't realize. 

Easy fix is to go back to a high fps conditional but maybe I can add a non-lag-adjusted time-adjust-ratio that stays at 1.0 for ntsc and 0.4 for 150fps regardless of lag?

 ```(ocean-interp-wave *ocean-heights* (the uint (* (-> *display* time-adjust-ratio) (-> *display* integral-frame-counter)))) ;; changed for high fps``` 

I probably need to change this everywhere :(
