### ISSUE TITLE
[Audio] Menu sound effects off centre (original game bug)

### ISSUE THREAD

**Issue by BreakPoints** [open-goal/jak-project#1556]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

For the main menu all UI sound effects only come through on the right channel until, strangely, the town transitions to night in which the menu sounds also smoothly move from right channel only to left channel only (found out by pausing and unpausing repeatedly).

Issue is present on PCSX2 so would seem to be an original game bug.

### How To Reproduce

Press start on the menu while listening on stereo speakers. Wait until night and try again to hear the sounds move channel.

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

All sounds should be centre, playing equally loud on both channels.

### Operating System

Windows 10 21H2

### OpenGOAL Version

0.1.12

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by ManDude** [comment]
I looked into this a bit.

`sound-play-by-name` has a `trans` argument, which when `#t` picks the caller's `trans` as the sound source, when `#f` it just picks the ear trans (e.g. not positional) and otherwise just uses that as the source vector directly. Almost every sound effect just uses the default `#t` argument.

Fixing that for the progress menu however still doesn't work. It appears that, while `(ear-trans)` and `(camera-pos)` stay frozen during the title, `(camera-angle)` does not and it messes up the panning. Not sure how to fix this, honestly.

**Comment by water111** [comment]
Sounds like this one is in the original game.
