### ISSUE TITLE
decompiler: type analysis should be able to use `type?` checks to inform the type of a variable

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#1818]
For example, the following code in `settings`
```mips
    lw t9, type?(s7)          ;; [834] (set! t9-34 type?) [] -> [t9: (function object type symbol) ]
    or a0, s3, r0             ;; [835] (set! a0-146 s3-1) [s3: process ] -> [a0: process ]
    lw a1, process-focusable(s7);; [836] (set! a1-59 process-focusable) [] -> [a1: <the etype process-focusable> ]
    jalr ra, t9               ;; [837] (call! a0-146 a1-59)
                              ;; [a0: process a1: <the etype process-focusable> t9: (function object type symbol) ] -> [v0: symbol ]
    sll v0, ra, 0

    beq s7, v0, L59           ;; [838] (b! (not v0-34) L59 (set! a0-147 #f)) [v0: symbol ] -> [a0: '#f ]
    or a0, s7, r0

B141:
    or a0, s3, r0             ;; [839] (set! a0-147 s3-1) [s3: process ] -> [a0: process ]
B142:
L59:
    beq s7, a0, L60           ;; [840] (b! (not (the-as process a0-147)) L60 (set! s3-2 #f)) [a0: process ] -> [s3: '#f ]
    or s3, s7, r0

B143:
    daddiu v1, s7, #t         ;; [841] (set! v1-211 #t) [] -> [v1: symbol ]
    sw v1, 256(s5)            ;; [842] (s.w! (+ s5-1 256) v1-211) [v1: symbol s5: cam-setting-data ] -> []
    daddiu s3, s5, 272        ;; [843] (set! s3-3 (+ s5-1 272)) [s5: cam-setting-data ] -> [s3: vector ]
    lwu v1, -4(a0)            ;; [844] (set! v1-212 (l.wu (+ a0-147 -4)))
                              ;; [a0: process-focusable ] -> [v1: <the type process-focusable> ]
    lwu t9, 96(v1)            ;; [845] (set! t9-35 (l.wu (+ v1-212 96)))
                              ;; [v1: <the type process-focusable> ] -> [t9: <vmethod (function process-focusable int vector)> ]
```

The variable has to be manually cast to a `process-focusable` despite the call to `type?` ensuring that it is as such.

**Comment by water111** [comment]
This is definitely doable but doesn't fit into any existing decompiler analysis passes so is a bit of effort.  That said, if anybody wants to contribute to the decompiler this is probably a nice issue to start on because it would be isolated from all the existing complicated stuff.

I think this could be done with three steps:

First, identify calls to `type?`. For each call, figure out which variable is being checked (in this case `s3`) and the block that is reached if the `type?` check passes (in this case B141).  Due to the coloring moves inserted by the compiler, possible stack spills, nested function calls, and nesting `type?` inside of more complicated expressions, this might not be easy. But I bet a simple check can catch most common cases.

Second, find all basic blocks which are dominated by B141. See https://en.wikipedia.org/wiki/Dominator_(graph_theory)
These are blocks that we can reach after the `type?` check passes, and _might_ have `s3` containing the given type.

Third, we need to correctly handle the case where another value is written to `s3`, and the result of the type check is no longer valid. This could be done by iterating over all the dominated blocks and doing:
- if an instruction writes to `s3`, flag that op as not passing the type check, then flag all successor basic blocks as not passing
- for each basic block that is flagged, flag all instructions in that block, then flag all successor blocks.
- repeat until stuff stops changing
this is basically doing a search to see which operations are dominated by an operation that writes something else to `s3`, and flagging those as not passing the type checks.

finally - insert casts on ops that are:
- in basic blocks that are dominated by B141
- not flagged
- read `s3` (or are function calls that might read a register, but we don't know yet)

The reason this is a bit of work to set up is again ordering issues. We'd be able to do this more easily in the register->variable pass where things are in SSA form, but we can't put things into SSA form until we know how many arguments each function call uses, but we can't know that until we figure out types.
