### ISSUE TITLE
decompiler: `vector-dot` recognition fails when the stack is involved.

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#1819]
This may be a more common thing in jak 2, we will see as time progresses, but it's still an issue:
```lisp
            (let* ((v1-10 s1-0)
                   (f0-6 (-> v1-10 x))
                   (f1-0 (-> v1-10 y))
                   (f2-0 (-> v1-10 z))
                   (f3-0 (-> sv-160 x))
                   (f4-0 (-> sv-160 y))
                   (f5-0 (-> sv-160 z))
                   )
              (.mula.s f0-6 f3-0)
              (.madda.s f1-0 f4-0)
              (.madd.s f0-7 f2-0 f5-0)
              )
```
in `v-slrp3!`

All instances found:
- "slave-set-rotation!",
- "v-slrp2!",
- "v-slrp3!"
- cam-los-collide

**Comment by ManDude** [comment]
I think this is because stack variables don't really get put into lets in general. They suck.

**Comment by water111** [comment]
My opinion is we should leave this as is because it would be quite a bit of effort to special case this, and that time would be better spent on something like https://github.com/open-goal/jak-project/issues/736 that would totally eliminate the problem.

these aren't too hard to fix manually `(set! f0-7 (vector-dot v1-10 sv-160))` and this looks like one that's also in jak 1. But definitely update this issue if we start seeing a bunch of new ones in jak 2.

**Comment by water111** [comment]
closing in favor of https://github.com/open-goal/jak-project/issues/736
and because we don't see too many of these, I don't think it's worth special-casing in meantime.
