### ISSUE TITLE
[linux] Runtime locks up for 30 seconds after input when a controller is plugged in with Steam running

### ISSUE THREAD

**Issue by legendddhgf** [open-goal/jak-project#1890]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

on SteamOS, Game starts up immediately without loading when run through steam as a non-steam game (gk executable after having extracted the ISO with extractor at least once). As a result, the first user input provided puts the game into a glitched state that has to be killed through a task manager (I just used kill $(pgrep gk))

### How To Reproduce

Add gk executable as non-steam game (gk executable) on steam os and run it through steam (doesn't matter whether in desktop mode or game mode, still same issue). I have found that running it out of steam, after having it run through steam this way once makes it skip loading permanently as well. The only workaround I have found is to re-run extractor and then run gk (but not through steam, so it has to be in desktop mode unfortunately).

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Waits a while before starting the game and then works as expected.

### Operating System

SteamOS

### OpenGOAL Version

1.5.0

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by Hat-Kid** [comment]
I run the game on my Deck with launch options `-boot -fakeiso -debug` and it works fine through Steam. Try that to see if it helps?

Removing them, I can't replicate exactly this behavior, but it just ends up immediately starting the game in the background, never being put in the foreground and I can start multiple instances and have to reboot the Deck to fix it.

**Comment by legendddhgf** [comment]
This didn't work (same stuck glitch the moment I enter a input) but I will note that the version number printed on the top left is v0.1.29

**Comment by legendddhgf** [comment]
I also have ssh enabled so that I can kill all instances of the game if anything happens with:

kill $(pgrep gk)

**Comment by legendddhgf** [comment]
In the end, an update ended up resolving these issues, and I recall these boot options making the game run worse. I would have to check what my current boot options are to confirm, will post when I do.

**Comment by Hat-Kid** [comment]
I believe that what you experienced is the same thing I started encountering somewhat recently on my Linux machine. Whenever I start OpenGOAL and plug my controller in when Steam is open, the very first input will cause the game to freeze for exactly 30 seconds before continuing as normal every time.

I'm not sure why this would happen on the Deck (never experienced it myself), but I'll reopen the issue as this seems to be an actual bug that, after a bit of investigation by @Ziemas, may have been introduced with the addition of vibration support in #1605.

And as for the game immediately starting without loading, that is simply what happens when starting the game in debug mode. You should be able to simply run the game without any launch flags and it should boot with the intro.

**Comment by legendddhgf** [comment]
I don't think you understood my situation correctly, so let me clarify a few things:

1. At time of filing this ticket, the game starting immediately without loading didn't happen as a result of running debug mode. It just started happening one day without warning, whereas it had previously worked fine but after some ~10 seconds of loading (not freezing, it hadn't started the game yet during this time frame).
2. After filing this ticket, I realized that the freezing after the first input that started happening after the "game start[ed] immediately without loading" (as described in 1.) did indeed stop after ~30 seconds. However, the next input would send it into a similar freeze, effectively making the game unplayable.
3. Even after filing this ticket and considering alternate launch options as you have suggested, the only workaround that was successful was the one I mentioned above regarding re-running extractor in desktop mode (I still don't know why that did anything at all).
4. To follow up, I just double checked and it is still running just fine with no launch options, in game mode (desktop mode not required), and with an immediate load time. This behavior (which I would describe as "ideal" or "without issue") actually started happening about a month or two ago, but I unfortunately only just remembered about this ticket earlier today (and decided to update it).


Perhaps the name you have now renamed this issue to as well as its reopening are adequately describing an issue others are still experiencing. However, it may also be possible that the issue I described or the issue you described have been fixed in some recent version. Whatever the case may be, as I have said in 4., the issue I originally described when filing the ticket is no longer happening to me (and much like the occurrence of 1., it just suddenly started working one day without needing to re-run extractor).


I am happy to provide additional information if you have questions. Otherwise, I will let you take care of closing this bug when you think it is appropriate.

**Comment by Hat-Kid** [comment]
I misunderstood your first point about the game immediately starting without loading, I assumed you were referring to the game immediately dropping you in Sandover Village after launching it.

The main reason I reopened the issue was to only keep track of the bug I described without opening a duplicate issue, as it seemed very similar to the issue you were experiencing (with the exception of it only happening once whenever a controller is plugged in instead of constantly like in your case) and all your other issues have already been resolved with a rerun of the extractor.
