### ISSUE TITLE
Decompiler does not support `return-from-thread`

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#1903]
This was an area that was never improved in jak 1 https://github.com/open-goal/jak-project/blob/dc5dc9c76ceb7b139ee6a2d1886a352335be4f94/goal_src/jak1/engine/anim/aligner.gc#L27-L28
And the code is the same in jak 2, not sure if we ever found another instance of this to make it worth it -- but I'm also surprised that nothing went wrong with that code commented out - https://github.com/open-goal/jak-project/pull/1901

```lisp
(.lw ra-0 return-from-thread s7-0)
(.jr ra-0)
```

**Comment by ManDude** [comment]
Not sure it's worth it. This is asm to return from a process's thread back to the kernel thread. Outside of the kernel code, this only occurs in that one file. The kernel instances were all manually fixed since it's a bunch of asm:

https://github.com/open-goal/jak-project/blob/master/goal_src/jak2/kernel/gstate.gc#L443
https://github.com/open-goal/jak-project/blob/master/goal_src/jak1/kernel/gkernel.gc#L598
https://github.com/open-goal/jak-project/blob/master/goal_src/jak1/kernel/gkernel.gc#L2512

The code here has a `(go process-drawable-art-error "align joint-anim")` and only runs when something goes wrong, which is why commenting it doesn't break anything (nothing breaks that ends up triggering it anyway). Since this method can also be called from a `post` handler, the `return-from-thread` call needs to be there so that the temporary thread can be abandoned immediately, as a `go` in a `post` won't exit the thread.

**Comment by ManDude** [comment]
that said... actually fixing it manually is probably pretty simple since the opengoal version of that code is right there
