### ISSUE TITLE
[everything] option to turn off ASCII coloring

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1917]
It looks very nice, but tools like git and jenkins' consoles don't display it properly so it looks like a total mess.

**Comment by xTVaser** [comment]
I actually changed the jenkins so that the colors are viewable in the "full output", ie. https://jenkins.opengoal.dev/job/jak-project/368/consoleFull

As for the CI, that is only an issue on the windows terminals, ive searched for a long time to find a solution but havn't been able to find one.

But yeah, this would be a nice opt-out feature for other situations.
