### ISSUE TITLE
Incorrect accessing with inline arrays of basics 

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#1951]
Noticed all over `hud`, here is a simple function that actually decompiles to illustrate the issue

```clj
(defmethod hud-method-26 hud ((obj hud) (arg0 int))
  (if (not (-> obj strings arg0 type))
      (set! (-> obj strings arg0 type) (the-as type (new 'process 'string 32 (the-as string #f))))
      )
  0
  (none)
  )
```

```clj
(deftype hud-string (basic)
  ((text  string           :offset-assert 4)
   (scale float            :offset-assert 8)
   (color uint32           :offset-assert 12)
   (flags uint32           :offset-assert 16)
   (pos   vector4w :inline :offset-assert 32)
   )
  :method-count-assert 9
  :size-assert         #x30
  :flag-assert         #x900000030
  )

(deftype hud (process)
  ((trigger-time   time-frame      :offset-assert 128) ;; time-frame
   (last-hide-time time-frame      :offset-assert 136) ;; time-frame
   (offset         float       :offset-assert 144) ;; int32
   (flags          hud-flags   :offset-assert 148)
   (values         hud-value  8 :inline :offset-assert 152)
   (strings        hud-string  14 :inline :offset-assert 288)
...
```

The type definition seems correct when cross-referencing the inspect methods, and the types of `hud-string` and such are definitely `basic`s.  It seems far more likely this method is supposed to be accessing the `text` field, not the `type` field.

This problem can even be seen in the inspect method:
1. if the fields aren't given a high score, it will access the dynamic `stack`
2. if they are, it accesses the type

```clj
  (format #t "~2Tflags: ~D~%" (-> obj flags))
  (format #t "~2Tvalues[8] @ #x~X~%" (&-> obj values 0 type))
  (format #t "~2Tstrings[14] @ #x~X~%" (&-> obj strings 0 type))
  (format #t "~2Tsprites[30] @ #x~X~%" (-> obj sprites))
  (format #t "~2Ticons[2] @ #x~X~%" (&-> obj stack 2752))
```

**Comment by water111** [comment]
This is weird - the alignment of the basics is just "wrong". This means that you can't print the correctly with `~A`, and attempting to access the `quad` field of `pos` would have crashed the PS2.

I think I can work around this by:
- make `allow-misaligned` work on basics, allowing them to be less-than-8-byte-aligned (which is kinda sketchy, but what can we do)
- replace those `pos` `vector4w`'s with just `int32 4`. If this has problems (like they try to `lq` from it), then it means we're not understanding something. I think this should never happen because it would load the wrong data on ps2.

I'll give this a try.
