### ISSUE TITLE
Constructing stack arrays is not yet supported

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#2016]
Usage found in `gun-dark-shot` where an array of `collide-shapes` is created:
```asm
lw v1, array(s7)          ;; [101] (set! v1-25 array) [] -> [v1: <the etype array> ]
    lwu t9, 16(v1)            ;; [102] (set! t9-9 (l.wu (+ v1-25 16)))
                              ;; [v1: <the etype array> ] -> [t9: <new array (function symbol type type int array)> ]
    daddiu a0, sp, 160        ;; [103] (set! a0-15 (+ sp-0 160)) [sp: <uninitialized> ] -> [a0: array ]
    lw a1, array(s7)          ;; [104] (set! a1-7 array) [] -> [a1: <the etype array> ]
    lw a2, collide-shape(s7)  ;; [105] (set! a2-4 collide-shape) [] -> [a2: <the etype collide-shape> ]
    addiu a3, r0, 16          ;; [106] (set! a3-3 16) [] -> [a3: <integer 16> ]
    jalr ra, t9               ;; [107] (call! a0-15 a1-7 a2-4 a3-3)
```

**Comment by water111** [comment]
also `target-part.gc`, in process-drawable-shock-skel-effect

**Comment by xTVaser** [comment]
Stack arrays are now supported, you have to cast the result manually unfortunately but the feature definitely works now
```clj
(let ((s3-0 (the-as (array collide-shape) (new 'stack 'array collide-shape 16)))
        (a1-8 (new 'stack-no-clear 'sphere))
        )
    (set! (-> a1-8 quad) (-> self root-override trans quad))
    (set! (-> a1-8 r) (-> self blast-radius))
```

**Comment by xTVaser** [comment]
Nevermind, this is still a problem, the method above that i tested was just omitted in the REF tests -- it was manually cast to a pointer array and uses `'stack-no-clear` instead of `'stack`

**Comment by water111** [comment]
I removed this from jak 2 since we finished the decomp there.

Still an issue for jak 3...

**Comment by ManDude** [comment]
What's the blocker here?

**Comment by xTVaser** [comment]
I don't believe there's a blocker, just support has to be added to the decompiler (I think the compiler now supports it? if not, then end-to-end)

**Comment by water111** [comment]
I don't think this is supported in the compiler. The feature is to create a GOAL array (the one that's a `basic`) that is stored on the stack, with a fixed size that is known at compile time. Basically you need to call the `new` method of `array`, but instead of passing it a heap like `global`, you'd pass it a pointer to stack memory. The size of the stack memory has to be something like `size_of_array_type + num_elements * element_size`.

I suspect this does work in the decompiler (possibly missing some casts) because we do support constructing basics on the stack. The reason why arrays are special is because the size of the stack allocation is more complicated.

There's no blocker to actually implementing it. The feature wasn't used very often and we got away with not having it for jak 2.
