### ISSUE TITLE
Arrays of `type`s are not supported by the compiler

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#2060]
`target-h`

```asm
L1:
    .type array
L2:
    .word 0x5
    .word 0x5
    .type type
    .type pilot-info
    .type mech-info
    .type turret-info
    .type indax-info
    .type tube-info
```

**Comment by water111** [comment]
do you know if there's another place this happens? This stupid list was also in jak 1 but nothing used it so we just skipped it. If it's the same for jak 2 maybe we can skip it too. I think I skipped it because we'd have to mess with the linker to support a new case of inserting references to types.

**Comment by xTVaser** [comment]
Looks like no, if my regex is to be believed
![image](https://user-images.githubusercontent.com/13153231/209259386-780db3a2-675e-41a8-aa66-377e4d404f3e.png)
