### ISSUE TITLE
[sprite-glow] MSAA breaks renderer

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#2249]
The more samples used for MSAA, the worse the effect gets. 2x already makes it nearly non-existent.

Off:
![image](https://user-images.githubusercontent.com/7569514/221341676-4b3ce991-9035-47a5-b8fd-05e4f4d4cdc2.png)

2x:
![image](https://user-images.githubusercontent.com/7569514/221341684-5786b02f-3652-4587-8d21-feb1912abcc1.png)

4x:
![image](https://user-images.githubusercontent.com/7569514/221341690-0f83bad8-56c1-4d81-a2e1-e7699b6e82e4.png)

**Comment by BreakPoints** [comment]
This is either fixed or a hardware specific issue. Note: small variations in brightness of lamps are due to flicker effect.
Results on a Windows 11 - RTX 2080

None:
![OpenGOAL - Work in Progress - rev  2ca297 28_02_2023 3_47_10 PM](https://user-images.githubusercontent.com/11966090/221905815-811f52e1-e2e1-4e52-a306-ac8fbbde934d.png)

2x:
![OpenGOAL - Work in Progress - rev  2ca297 28_02_2023 3_47_21 PM](https://user-images.githubusercontent.com/11966090/221905879-d8cd8f4d-6f8b-4bc4-8822-4bbb2df4d3a4.png)

4x:
![OpenGOAL - Work in Progress - rev  2ca297 28_02_2023 3_47_29 PM](https://user-images.githubusercontent.com/11966090/221905925-18d86789-a3b8-4f1a-9dbb-daecb3e61324.png)

**Comment by Zedb0T** [comment]
I can also confirm that this seems to either be fixed on master, or it has some other factors at play too.

https://user-images.githubusercontent.com/89345505/227757416-8920bcaa-5c08-48b8-9d68-225c18506f3e.mp4

**Comment by ManDude** [comment]
It's still broken for me.

**Comment by ManDude** [comment]
![image](https://user-images.githubusercontent.com/7569514/232173489-1462299c-5af3-4e1e-9af0-50fa9586d8de.png)
Also happens with letterboxing.

**Comment by ManDude** [comment]
Fixed by making the glow renderer copy the depth24+stencil8 buffer instead of just depth24, which I think was incorrect usage anyway since the buffer it copies from should have a stencil8 attached for the shadow renderer.
