### ISSUE TITLE
dark square sprite around krew lens, precursor stone and warp gate warp effect

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#2410]

**Comment by water111** [comment]
Fixed by #2415 

precursor stone:


![Image](https://user-images.githubusercontent.com/48171810/227746706-64e3c074-043d-4966-b76f-97178490d6e8.png)

warp gate


![Image](https://user-images.githubusercontent.com/48171810/227746813-79727914-9ee4-443d-b9f3-1b1620292921.png)

krew


![Image](https://user-images.githubusercontent.com/48171810/227746829-3402e33c-93cb-42d3-a502-f87709d01a41.png)
