### ISSUE TITLE
[Jak1] emerc regression on stone sculptor face guard

### ISSUE THREAD

**Issue by BreakPoints** [open-goal/jak-project#2451]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

_The Dude_ might have a hard time sculpting rock with a fully opaque face guard.

![image](https://user-images.githubusercontent.com/11966090/229564395-5599405e-b229-4472-9394-5de502cc4939.png)

### How To Reproduce

Find the stone sculptor and stare at his face guard

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Should be partially transparent but still shiny

### Operating System

Windows 11 22H2

### OpenGOAL Version

0.1.34

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by ManDude** [comment]
emerc bug, not etie.

**Comment by water111** [comment]
oops, good catch. I started looking into this. It's a similar case to broken red rings, where there's some generic-only magic to change a blending mode that doesn't work in merc. My guess is that if you get far away from the sculptor in the original game, it switches to merc and becomes not-transparent.

I believe that generic runs with alpha blending on, but overrides the adgif-shader with `alpha-opaque` `ad-cmd` in `generic-consts` in most cases. So we need to figure out when this would happen, and do the same in our PC Merc implementation.

Searching for offsets shows that there's some tricky stuff in `mercneric-convert` that reads this array of `ad-cmd`s:
```
;; t2 is the scratchpad, this is accessing generic-work.
lbu a1, 6827(t2)
    addiu a2, r0, 4
    lw t0, 7316(t2)
    sll r0, r0, 0
    lw v1, 7320(t2)
    dsubu t4, a1, r0
    lw a1, 40(t2)
    ;; 6772 - (16 + 624 + 5952 + 128) -> 52 in merc-header
    movn a0, a2, t4
    lbu t3, 6772(t2)
    daddu t1, a0, t2
    lw a0, 7300(t2)
    daddiu a2, a1, 128
    lbu a3, 10(t0)
    dsll t5, t3, 1
    lbu t3, 9(t0)
    daddu t1, t1, t5 ;; some index
lbu t5, 11953(t1)
    sll r0, r0, 0
    lbu t6, 11952(t1)
    sll r0, r0, 0
    lw t1, 7304(t2)
    sll t7, a3, 4
    daddu t6, t6, t2
    daddu t8, t5, t2
    lw a3, 7308(t2)
    daddu t5, t7, t0
    sw t5, 7324(t2)
    sll r0, r0, 0
    lbu t0, 12(t5)
    addiu t7, r0, 0
    lq t8, 11888(t8) ;; loading the replacement
    movn t7, r0, t4
    lq t4, 11888(t6) ;; loading the replacement
```
The index is computed from `merc-effect.envmap-usage` (makes sense) and `merc-ctrl-header.use-translucent`. This `use-translucent` is part of the "dummy-bytes". These have been a mystery because they actual contain other information (in the case of `use-translucent`, it's actually `shader-upload-count`). 

But I think I get it now - when merc data is renderered by generic, the `merc-effect` is copied to the scratchpad for processing, then something overwrites these dummy-bytes with generic specific stuff. Now I just need to find that overwriting...

**Comment by water111** [comment]
Should be fixed in https://github.com/open-goal/jak-project/pull/2458. It turns out the "dummy" flags are set in `draw-bones-generic-merc`.

**Comment by BreakPoints** [comment]
Thought I would take the opportunity to test the new launcher. Slapped a new build into the devel folder and confirmed the fix.

![Uploading image.png…]()

**Comment by BreakPoints** [comment]
Thought I would take the opportunity to test the new launcher. Slapped a new build into the devel folder and confirmed the fix.

![Screenshot 2023-04-06 025606](https://user-images.githubusercontent.com/11966090/230253313-829c6285-5eed-4c6d-8a62-e4328b6470b5.png)
