### ISSUE TITLE
Speedrunner mode no longer skips sage-intro

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/jak-project#2871]
Observed on 426851720f4f575f5abc9b20eb9739c8ed8edf5c likely happens in commits before this

**Comment by xTVaser** [comment]
This is the commit that caused the regression - https://github.com/open-goal/jak-project/commit/da3caf7b2850c37eb7801221461bb8ff918fa101

Also it seems like it doesnt start properly via `Continue Without Saving` for a while as well...most likely another regression going back a while or im forgetting if that ever used to work.

Should probably release this fix under a separate/new tag since 0.1.39 has been out for a while.  I don't want to cause people being on the "wrong" 0.1.39.
