### ISSUE TITLE
Music cuts out too aggressively when completing `forest-protect`

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#3033]

**Comment by ManDude** [comment]
is this still an issue? I'm not too familiar with the intended behavior.

**Comment by Hat-Kid** [comment]
If this refers to the game playing the high danger variant of the forest theme, this also happens on PS2 and it's probably because the excitement level is maxed during the mission and resets once complete.

Incidentally, I think this is also the only instance in the game where you get to hear that variant, if only for a second.

**Comment by ManDude** [comment]
Assuming fixed.
