### ISSUE TITLE
Extractor.exe does not respect permissive_redefinitions when compiling the project

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/jak-project#3566]

**Comment by xTVaser** [comment]
The `extractor.exe` does not load any of the REPL config because it's not intended to be a REPL environment.

`permissiveRedefinitions` is to reduce friction during common REPL/development situations -- like changing a function definition, or the fields in a type, etc.  It should not be used or needed during a full-project compile, your code should instead cleanly compile end-to-end.  

If you think it's actually needed....I'd be interested in seeing an example cause by-and-large most languages do not allow for this behaviour and it does not feel like a burden (the opposite is true infact, in languages where you can just monkey-patch things wherever you want)
