### ISSUE TITLE
[jak3] texture animations catch-all

### ISSUE THREAD

**Issue by Hat-Kid** [open-goal/jak-project#3582]
Most texture animations have been added and work, but a couple of issues still remain:

- [x] ~~`hanga-sprite`: Despite `move_to_pool` being set for this anim, it's not showing up in-game, but it does display properly in the ImGUI debug window.~~
![image](https://github.com/open-goal/jak-project/assets/6624576/29df8e17-8831-412b-b9b7-7704d6bd7813)
- [x] ~~`factoryc-alpha`: Some conveyors do not have the animation for some reason.~~ We were missing TIE support for texture animations.
![image](https://github.com/open-goal/jak-project/assets/6624576/209ef073-2a81-4e2c-b020-dc2ae0b01196)
- [x] ~~This spot in Spargus seems to use texture animations, but it looks like it maps to the `fora-water-dest` texture/slot, which comes from `foresta-water`. Because the texture is not initialized, the texture shows up black on first load, but it does show up after loading `foresta`.~~
![image](https://github.com/open-goal/jak-project/assets/6624576/1e54bab2-f97c-47d5-a92a-a98a52c30178)
![image](https://github.com/open-goal/jak-project/assets/6624576/240b0137-1e9e-4e65-8446-0f78df9802dd)
- [x] ~~`hfrag` texture anim is not handled yet. Probably needs some special casing.~~
- [x] ~~`darkjak-highres`: Eye texture slot animates, but the model still uses the default eye texture.~~

**Comment by TomChapple** [comment]
> [!WARNING]
> I have very little experience here so it is likely I may be misinterpreting something.

On the topic of "hanga-sprite", I'm curious if "glider-ring-dest" should contain "glider-ring-dest2" within its texture data in that ImGui screenshot.

Looking at the dynamic data, "glider-ring-dest" refers to "glider-ring-dest2" in the first element (layer?). Each layer is interpolated, so it makes sense to me that it is pulling from this other animated texture. I'm tempted to compare this to the part "group-forest-ring", but there are some minor differences that look like it will act differently. Nevertheless, I haven't found a function call that will warp me to "foresta-ring-chase" to compare them.

**Comment by TomChapple** [comment]
I have been doing some thinking about the difference in hue from the little test I did and the vanilla game. When I look back at TextureAnimator, I didn't see any configuration for manipulating the texture's colour. The "gilder-ring-dest2" definitely takes advantage of this, even setting the blue component to about twice its usual value.

Has blending animated textures with colour been implemented? If it isn't, that would explain why the hue is off. I totally expect that I have missed it somewhere.

**Comment by TomChapple** [comment]
I was able to discover how colour blending is implemented, so I have answered my own question. I didn't realise that the static data was defined again in `TextureAnimatorDefs.cpp` but the dynamic data (including the colour) was loaded in from DMA. At least I now have a point of reference to go from.

**Comment by water111** [comment]
Hey @TomChapple - sorry I totally missed these comments!  

Thanks for taking a look through our somewhat questionable `TextureAnimator.cpp`. I think we have this working now, and your ideas were all correct. 

> Changing the source texture for layer 0 of "glider-ring-dest" to match the destination texture of "gilder-ring-dest2" (currently hardcoded) results in the animated texture being visible in-game as seen below.

Yep - this was basically the issue. The `glider-ring-dest` layer 0 referenced the output of animation `glider-ring-dest2`, but the texture animator didn't support this case. Instead, it just gave you the non-animated texture named `glider-ring-dest2`. I've got a fix for that here: https://github.com/open-goal/jak-project/pull/3732

> I have a feeling that something is intended to happen between writing to the destination texture in "glider-ring-dest2" and using the source texture in "glider-ring-dest", maybe some other form of interpolation to change the hues and intensities.

Right again. The final layer in the original game code sets `:func-id 'set-alpha-texture-anim-layer-func` instead of the normal `default-texture-anim-layer-func`.  The `set-alpha` version will modify the `glider-ring-dest2` to set the alpha channel to 128.  This was missing from the definition in `TextureAnimatorDefs.cpp`, so the alpha ended up being a much smaller value, making the ring look washed out.  When `glider-ring` uses `glider-ring-dest2`, it ends up multiplying the RGBA of `glider-ring-dest2` by the texture's alpha, so if the alpha is wrong, the colors end up wrong.

**Comment by TomChapple** [comment]
That's awesome to see that working now! It's all good about the comments, they were only there to avoid retreading ground if possible (though I was definitely aware that they may have been obvious to frequent contributors). Seeing that `''set-alpha-texture-anim-layer-func` change the alpha channel further is definitely interesting, though!

Thanks for responding, I definitely want to look at this a bit more in the future and your response is very encouraging to do so! I should try and get my dev environment setup again at some point, but Nix is definitely a different beast to what I'm used to.
