### ISSUE TITLE
[jak3] 'Not reached' assertion failed in overlord when booting, 'Invalid VAG data'

### ISSUE THREAD

**Issue by atylmo** [open-goal/jak-project#3623]
Hi. I'm using Ubuntu and I can compile the project, but when I run it I get the following message (a few preceding lines for context):

```
WARNING: enemy::move-to-ground: failed to locate ground for citizen!
[00:33:182] [warn] [[405] gmerc2-lcom-pris] OpenGL warn 0x20092 S8246 T8250: Program/shader state performance warning: Vertex shader in program 42 is being recompiled based on GL state.
[00:33:247] [warn] --------------- LoadSoundBankToIOP END
Elapsed time for level =       0.2666s
NOTICE: loaded wasstada, 2367008 bytes (2311.5312 K) at top 3817392 at #x29e7e00 - #x2c29c60
Unload soundbank empty2 from slot 4
Load music wascity
Adding level wasstadb
Starting level load clock
Load soundbank wascity3 in slot 4
[00:33:264] [info] DGO RPC: new command ID, starting a load for wasstadb.DGO

[00:33:264] [info] DGO RPC: CancelDGO NO CMD

[00:33:264] [info] ------------------DGO: RPC sending mbox (reply size is 0)
[00:33:264] [info] DGO: RPC waiting mbox (now has 0)
[00:33:264] [warn] --------------- LoadSoundBankToIOP START
[00:33:265] [info] Incoming message to the ISO Queue with type 0x200
[00:33:265] [info] Opening WASSTADBDGO for DGO Load
[00:33:265] [info] ProcessMusic is changing the music to wascity
[00:33:265] [info] vag dir entry offset is 5653
[00:33:265] [debug] CDvdDriver swapping files WWD     DGO - > VAGWAD  INT
[00:33:265] [debug] CDvdDriver jumping in file VAGWAD  INT: 0 -> 185237504
[00:33:268] [error] Invalid VAG data is 0x0
[00:33:268] [die] Assertion failed: 'not reached'
	Source: /home/ty/Downloads/jak-project-master-jak3-4-gitpull/jak-project/game/overlord/jak3/spustreams.cpp:210
	Function: jak3::EIsoStatus jak3::ProcessVAGData(jak3::ISO_Hdr *)

task: Failed to run task "boot-game": exit status 134
task: Failed to run task "boot-game": exit status 134
```
If I run `boot-game-retail` then I get this (potentially completely unrelated):
```
[17:25:807] [die] Assertion failed: 'offset'
	Source: /home/ty/Downloads/jak-project-master-jak3-4-gitpull/jak-project/./game/kernel/common/Ptr.h:40
	Function: T *Ptr<jak3::Type>::operator->() [T = jak3::Type]

task: Failed to run task "boot-game-retail": exit status 134
task: Failed to run task "boot-game-retail": exit status 134
```

I know `overlord2` is still being worked on, but I wanted to report this to see if it was just me or specific to Linux.

**Comment by water111** [comment]
The problem is very likely caused by the file `VAG/VAGWAD.INT` being all zeros. For a reason that I don't understand, the default ISO extraction tool in ubuntu (and probably other linux distros) doesn't extract this file properly.

My guess is that if you use something like 7zip to extract the iso, you'll get a VAGWAD.INT that's not full of 0's, and the assertion will stop happening.

**Comment by atylmo** [comment]
Ah, thanks for the tip! I'll give it a try! And no worries, take your time :)

**Comment by atylmo** [comment]
I've tried recompiling and extracting it only on my internal drive (as opposed to on an external drive and copying the files over), but the issue persists. I'm using Ubuntu 22.04 LTS.

**Comment by water111** [comment]
can you check if `jak-project/out/jak3/iso/VAGWAD.INT` is all zeros? Check with something like `hexdump -C jak-project/out/jak3/iso/VAGWAD.INT`.

If that is all zeros, you could delete everything in `jak-project/out/jak3/iso/`, re-run `(mi)`, then try again.

My guess is that re-running `(mi)` didn't actually replace the VAGWAD.INT file in the `out/jak3/iso` folder, since `(mi)` looks at file timestamps to decide if it needs to rebuild, and both a good and bad VAGWAD.INT has the same modification timestamp.

**Comment by atylmo** [comment]
Interesting, I didn't have that file there. Or any `.VAG` files. I ran `hexdump` in `iso_data`, and `VAGWAD.INT` had data in it.

I just retried by deleting everything in the folder you mentioned and it copied them over and works now! I'm not sure what happened, unless I ran out of room on the disk when copying or RAM when recompiling (and doing it again didn't trigger a full refresh of the folder).

Thank you so much for your help :)
