### ISSUE TITLE
[decompiler] Function Analysis Tool for PCSX2

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#497]
Decompiling methods is really annoying for two reasons.  It's hard to find where a method is called from, making it hard to figure out argument types.  Sometimes you find code that calls a method, but you don't know the type, so you don't know what method is being called.

I had an idea for a tool that could find this information.  We could run the game in PCSX2 and collect data about each `jalr` (call) instruction and each function. For calls, we could collect:
- What possible functions are called from here? (methods or named functions)
- Are any arguments basics? If so, what type?

For each function, we would just collect a list of where its called from.

The rough process would be to first build a map that lets us quickly convert an address to an offset into a function, then add a hook to PCSX2's EE interpreter on `jalr`.  Each time we hit a `jalr`:
- store values of argument registers, `jalr` location, and destination
- If an argument register looks like a basic, read the type-tag.

Then, from this log and the map, we could figure out the information.

**Comment by xTVaser** [comment]
Added to this release under the "Tools" menu https://github.com/xTVaser/pcsx2-rr/releases/tag/128mb%2Fv2.0.3

There is very likely some caveats/edge-cases it's not detecting, and enabling it when starting the game seems to back the emulator up quite a bit (enabling it after it's booted is fine though).  But this provides a foundation to work from.

Supports jak 1 and jak 2, and runs in the recompiler instead of the interpreter so the game basically still runs at full speed.  The results are output as JSON so we can read them in with scripts.
